/**
 * Campaign Studio types — the data model behind the Veo video generation +
 * human review + publishing pipeline.
 */

export type CampaignStatus = "drafting" | "generating" | "ready_for_review" | "publishing" | "complete" | "failed";
export type JobStatus = "queued" | "running" | "succeeded" | "failed" | "cancelled";
export type Verdict = "pending" | "approved" | "rejected" | "starred";
export type Platform = "instagram_reel" | "tiktok" | "instagram_story" | "google_post";
export type PublishStatus = "draft" | "scheduled" | "posted" | "failed";

export type CampaignBrief = {
  id: string;
  pastrySlug: string;
  pastryName: string;
  hookType:
    | "behind_scenes"
    | "ugc_quote"
    | "menu_drop"
    | "limited_run"
    | "pairing"
    | "process_video"
    | "ranking"
    | "asmr"
    | "transformation";
  vibe: "luxe" | "playful" | "asmr" | "documentary" | "creator_pov" | "noir";
  audience: "tourists" | "regulars" | "wedding_planners" | "instagrammers" | "concierge";
  goal: string;
  variantCount: number;
  durationSec: 8 | 16; // Veo 3 = 8s; we can chain two for 16s reels
  aspect: "9:16" | "1:1" | "16:9";
  createdAt: string;
  status: CampaignStatus;
  notes?: string;
  /** Which ElevenLabs voice should narrate creator-POV stitches. Defaults
   * to env (Laura) if missing. Can be a preset voiceId or a cloned voiceId. */
  voiceId?: string;
  /** Optional cadence-style preset id (from voice-clone/styles.json) —
   * locks the SCRIPT (not the voice) to mimic a specific creator's rhythm. */
  styleId?: string;
  /** Content-bucket id (e.g. "asmr", "kitchen_montage", "ranking", "menu_drop").
   * When set, the script generator routes through the bucket's systemBrief
   * to produce the right SHAPE of content for that type. */
  bucketId?: string;
  /** BrandBrain client id. When set, every generated prompt + script is
   * passed through this brand's voice profile so output sounds like THEM. */
  clientId?: string;
  /** What kind of post are we making?
   *   "video"    → Veo renders an 8/16-sec clip per variant (current default).
   *   "image"    → Nano Banana renders a single still per variant (IG single post).
   *   "carousel" → Nano Banana renders `slideCount` stills per variant,
   *                bundled together as one IG carousel post.
   */
  mediaType?: "video" | "image" | "carousel";
  /** When mediaType === "carousel": how many slides per variant (2–10). */
  slideCount?: number;
};

/**
 * A still image generated by Nano Banana for an image/carousel campaign.
 * Mirror of GeneratedVideo but without the duration / clipStitching plumbing.
 */
export type GeneratedImage = {
  id: string;
  campaignId: string;
  promptId: string;
  variantIndex: number;       // which variant this image belongs to (0-based)
  slideIndex: number;         // which slide within the carousel (0-based; 0 for single image)
  prompt: string;             // the Nano Banana prompt
  caption: string;            // the IG caption (shared across slides for a carousel)
  hashtags: string[];
  imageUrl: string;           // /generated/img-... (served from public/)
  aspect: "1:1" | "4:5" | "9:16" | "4:3";
  generatedAt: string;
  verdict: Verdict;
  reviewedAt?: string;
  reviewerNote?: string;
  qualityScore: number;
};

export type VeoPrompt = {
  id: string;
  campaignId: string;
  index: number;
  prompt: string;        // the text-to-video prompt sent to Veo
  caption: string;       // the social-post caption (separate from video prompt)
  styleTag: string;      // human label e.g. "Tilt-down · golden hour"
  seedImage?: string;    // optional image-to-video seed (URL)
  hashtags: string[];
  // ─── Creator POV extension ─────────────────────────────────
  // When this prompt belongs to a Creator-POV variant, we need a stitching
  // plan: multiple shot prompts, a narration script, and total length.
  // The campaign worker spawns one Veo job per shot, then runs ffmpeg to
  // merge them with the ElevenLabs narration.
  creatorPov?: {
    narration: string;
    /** Same as `narration` plus inline ElevenLabs v3 audio tags
     * ([breath] [chuckles] [pauses] etc). This is what we actually send
     * to TTS — `narration` is the clean transcript. */
    narrationVoiced?: string;
    hookLine: string;
    totalSeconds: number;
    shots: Array<{
      index: number;
      /** Verbatim substring of narration this shot is locked to — used at
       * stitch time to look up the real audio start/end timestamps. */
      narrationPhrase: string;
      startSec: number;
      endSec: number;
      prompt: string;
      onScreenText?: string;
    }>;
  };
};

export type VideoJob = {
  id: string;
  campaignId: string;
  promptId: string;
  status: JobStatus;
  provider: "veo3" | "veo3_fast" | "mock";
  externalJobId?: string;
  startedAt?: string;
  completedAt?: string;
  error?: string;
  /** For creator-POV multi-shot variants: the rendered clip URL gets stashed
   * here when the job succeeds, so the stitcher can find each shot. */
  clipUrl?: string;
};

export type GeneratedVideo = {
  id: string;
  jobId: string;
  campaignId: string;
  promptId: string;
  prompt: VeoPrompt;
  videoUrl: string;
  thumbnailUrl: string;
  durationSec: number;
  aspect: string;
  resolution: string;
  generatedAt: string;
  verdict: Verdict;
  reviewedAt?: string;
  reviewerNote?: string;
  qualityScore: number;  // 0..100, our post-generation auto-rating
  // Engagement forecast (calculated, not measured)
  forecast: {
    expectedReach: number;
    expectedEngagementRate: number;
    riskFlags: string[];
  };
};

export type ScheduledPost = {
  id: string;
  videoId: string;
  campaignId: string;
  platform: Platform;
  status: PublishStatus;
  scheduledFor?: string;
  postedAt?: string;
  externalPostId?: string;
  externalPostUrl?: string;
  caption: string;
  hashtags: string[];
};

/**
 * A user-composed final carousel. After approving individual image variants,
 * the user can hand-pick + reorder slides FROM ACROSS multiple variants into
 * the actual post they want to publish. This lives separately from the
 * generated `images` so the original generation evidence is preserved.
 */
export type ComposedCarousel = {
  id: string;
  campaignId: string;
  /** Ordered slide list — references existing GeneratedImage.id values. */
  slideImageIds: string[];
  caption: string;
  hashtags: string[];
  createdAt: string;
  updatedAt?: string;
};

/** Campaign + everything joined — what the UI consumes. */
export type CampaignDetail = {
  brief: CampaignBrief;
  prompts: VeoPrompt[];
  jobs: VideoJob[];
  videos: GeneratedVideo[];
  /** For image / carousel campaigns. Empty for video campaigns. */
  images: GeneratedImage[];
  /** User-composed final carousels — the actual posts they intend to ship. */
  composedCarousels: ComposedCarousel[];
  scheduledPosts: ScheduledPost[];
  stats: {
    totalPrompts: number;
    totalJobs: number;
    completedJobs: number;
    failedJobs: number;
    runningJobs: number;
    queuedJobs: number;
    videosReady: number;
    videosApproved: number;
    videosRejected: number;
    videosStarred: number;
    /** Carousel-aware: counts variants (carousel post = 1), not slides. */
    imageVariantsReady: number;
    imageVariantsApproved: number;
    imageVariantsRejected: number;
    imageVariantsStarred: number;
    postsScheduled: number;
    postsPublished: number;
  };
};
